const fs=require('fs'),vm=require('vm'),path=require('path');const ROOT=__dirname;
const elems=new Map(),local={};function fakeEl(id=''){if(elems.has(id))return elems.get(id);const x={id,innerHTML:'',textContent:'',dataset:{},classList:{toggle(){},add(){},remove(){},contains(){return false}},style:{},setAttribute(){},removeAttribute(){},addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},closest(){return null},appendChild(){},remove(){},click(){},focus(){}};elems.set(id,x);return x;}
const document={body:{classList:{toggle(){},add(){},remove(){}}},getElementById:fakeEl,addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},createElement:()=>fakeEl('created')};const navigator={userAgent:'QA',serviceWorker:{register:()=>Promise.resolve()},standalone:false};const window={matchMedia:()=>({matches:false}),navigator,document,addEventListener(){},print(){},confirm:()=>true};const ctx={console,TextDecoder,TextEncoder,Blob,File:class File extends Blob{constructor(bits,name,opts){super(bits,opts);this.name=name;}},URL,Date,Intl,Math,JSON,Set,Map,Object,Array,String,Number,Boolean,RegExp,localStorage:{getItem:k=>local[k]??null,setItem:(k,v)=>local[k]=String(v)},navigator,window,document,confirm:()=>true,setTimeout:()=>0,clearTimeout(){},fetch:async()=>{},crypto:globalThis.crypto};ctx.globalThis=ctx;
let code=fs.readFileSync(path.join(ROOT,'app.js'),'utf8').replace(/\bboot\(\);/g,'');code+=`\n;globalThis.__T={state,resolveItems,renderAbstract,renderGCATText,responseStore,storageId,modelAnswer};`;vm.createContext(ctx);vm.runInContext(code,ctx);const T=ctx.__T;
const read=f=>JSON.parse(fs.readFileSync(path.join(ROOT,'data',f),'utf8'));T.state.master=read('assessment_master_v1.json');T.state.banks={gcat_abstract:read('gcat-abstract-100-balanced-7sim.json'),gcat_numerical:read('gcat_numerical_100_selected_7mocks.json'),gcat_verbal:read('gcat_verbal_100_selected_7mocks.json'),pq10:read('personality_pq10_7_simulations_1008_ar_v9_app_ready.json'),derailers:read('derailers_7_simulations_420_ar_v6_app_ready.json'),leadership:read('leadership_sjt_master_v5_6_app_ready_double_checked.json')};
const css=fs.readFileSync(path.join(ROOT,'styles.css'),'utf8');
function save(name,title,fragment){const html=`<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css} body{max-width:430px;margin:0 auto;padding:0;background:#f5efe5} #questionHost{padding:12px}</style><body><header class="topbar"><div class="topbar-inner"><div class="brand"><strong>${title}</strong></div></div></header><main id="questionHost">${fragment}</main></body></html>`;fs.writeFileSync(path.join(ROOT,'qa_screenshots_v1_4',name+'.html'),html);}
fs.mkdirSync(path.join(ROOT,'qa_screenshots_v1_4'),{recursive:true});
// Analogy replacement Q061
let item;for(let i=1;i<=7;i++){item=T.resolveItems('M'+i,'gcat').find(x=>x.id==='Q061');if(item)break;}T.state.session={mid:item.sourceMid,module:'gcat',mode:'training',responseScope:'training',items:[item],index:0};T.renderAbstract(item);save('abstract_analogy_Q061','GCAT — تجريدي — علاقة',fakeEl('questionHost').innerHTML);
// Sequence sample
let seq=T.resolveItems('M1','gcat').find(x=>x.kind==='abstract'&&x.data.question_format==='sequence');T.state.session={mid:'M1',module:'gcat',mode:'training',responseScope:'training',items:[seq],index:0};T.renderAbstract(seq);save('abstract_sequence','GCAT — تجريدي — تسلسل',fakeEl('questionHost').innerHTML);
// Numerical feedback wrong
let num=T.resolveItems('M1','gcat').find(x=>x.kind==='numerical');T.state.saved={responses:{},results:{},fullResults:{},history:[],favorites:[],sessionMeta:{},reviewItems:{}};T.state.session={mid:'M1',module:'gcat',mode:'training',responseScope:'training',items:[num],index:0};let wrong='ABCDEF'.split('').find(x=>x!==num.data.correct_answer);T.responseStore('M1','gcat','training')[T.storageId(num)]=wrong;T.renderGCATText(num);let nh=fakeEl('questionHost').innerHTML.replace('<div id="feedbackHost"></div>',fakeEl('feedbackHost').innerHTML);save('numerical_step_by_step','GCAT — العددي — شرح تدريبي',nh);
console.log('rendered static QA html');
