const fs=require('fs'),vm=require('vm'),path=require('path');const ROOT=__dirname;
const elems=new Map();function fakeEl(id=''){if(elems.has(id))return elems.get(id);const x={id,innerHTML:'',textContent:'',dataset:{},classList:{toggle(){},add(){},remove(){}},style:{},setAttribute(){},removeAttribute(){},addEventListener(){},querySelectorAll(){return[]},closest(){return null},appendChild(){},remove(){},click(){},focus(){}};elems.set(id,x);return x;}
const local={};const ctx={console,TextDecoder,TextEncoder,Blob,File:class File{},URL,Date,Intl,Math,JSON,Set,Map,Object,Array,String,Number,Boolean,RegExp,localStorage:{getItem:k=>local[k]??null,setItem:(k,v)=>local[k]=String(v)},navigator:{userAgent:'QA',serviceWorker:{register:()=>Promise.resolve()},standalone:false,share:null},window:{matchMedia:()=>({matches:false}),navigator:{standalone:false},addEventListener(){},print(){}},document:{body:{classList:{toggle(){},add(){},remove(){}}},getElementById:fakeEl,addEventListener(){},createElement:()=>fakeEl('created')},confirm:()=>true,setTimeout:()=>0,clearTimeout(){},fetch:async()=>{throw new Error('no fetch')},crypto:globalThis.crypto};ctx.globalThis=ctx;
let code=fs.readFileSync(path.join(ROOT,'app.js'),'utf8').replace(/boot\(\);\s*$/m,'');code+='\n;globalThis.T={state,resolveItems,renderGCATTrainingHub,v13RenderGCATDomainHub,startSession,responseStore,storageId,renderGCATText,renderAbstract,renderLeadership,renderResult,renderMyAnswers,modelAnswer};';vm.createContext(ctx);vm.runInContext(code,ctx);const T=ctx.T;
function read(f){return JSON.parse(fs.readFileSync(path.join(ROOT,'data',f),'utf8'))}T.state.master=read('assessment_master_v1.json');T.state.banks={gcat_abstract:read('gcat-abstract-100-balanced-7sim.json'),gcat_numerical:read('gcat_numerical_100_selected_7mocks.json'),gcat_verbal:read('gcat_verbal_100_selected_7mocks.json'),pq10:read('personality_pq10_7_simulations_1008_ar_v9_app_ready.json'),derailers:read('derailers_7_simulations_420_ar_v6_app_ready.json'),leadership:read('leadership_sjt_master_v5_6_app_ready_double_checked.json')};T.state.settings={theme:'light',fontSize:'medium',timerVisible:true,onboardingSeen:true,resultView:'latest',resultScope:'exam'};
function clear(){for(const x of elems.values()){x.innerHTML='';x.textContent='';}}function composed(){let m=fakeEl('main').innerHTML,q=fakeEl('questionHost').innerHTML,f=fakeEl('feedbackHost').innerHTML;if(q){if(f)q=q.replace('<div id="feedbackHost"></div>',`<div id="feedbackHost">${f}</div>`);m=m.replace('<div id="questionHost"></div>',`<div id="questionHost">${q}</div>`);}return m;}
function shell(title,body){return `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="../styles.css"><style>body{padding-bottom:20px}.topbar{position:sticky}.main{max-width:850px}</style><body><header class="topbar"><div class="top-nav-actions"><button class="icon-btn">⌂</button><button class="icon-btn">‹</button></div><div class="title-area"><div class="eyebrow">منصة التدريب والمحاكاة</div><h1>${title}</h1></div><div class="top-actions"><button class="icon-btn">Aa</button></div></header><main class="main">${body}</main></body></html>`}
const outDir=path.join(ROOT,'qa_screenshots_v1_3');fs.mkdirSync(outDir,{recursive:true});
function save(name,title,body){fs.writeFileSync(path.join(outDir,name+'.html'),shell(title,body));}
clear();T.renderGCATTrainingHub();save('gcat_training_hub','GCAT — التدريب',composed());
clear();T.v13RenderGCATDomainHub('abstract');save('gcat_abstract_hub','GCAT — التجريدي',composed());
T.state.saved={responses:{},results:{},fullResults:{},history:[],favorites:[],sessionMeta:{},reviewItems:{}};
clear();T.startSession('M1','gcat','training',false);let seq=T.state.session.items.find(x=>x.kind==='abstract'&&x.data.question_format==='sequence');T.state.session.items=[seq];T.state.session.index=0;let st=T.responseStore('M1','gcat','training');st[T.storageId(seq)]='ABCDEF'.split('').find(x=>x!==T.modelAnswer(seq));T.renderAbstract(seq);save('abstract_sequence_wrong','التجريدي — تدريب',composed());
clear();T.startSession('M1','gcat','training',false);let mat=T.state.session.items.find(x=>x.kind==='abstract'&&x.data.question_format==='matrix');T.state.session.items=[mat];T.state.session.index=0;T.renderAbstract(mat);save('abstract_matrix','التجريدي — مصفوفة',composed());
clear();T.state.session=null;T.startSession('M1','leadership','training',false);let li=T.state.session.items[0],ls=T.responseStore('M1','leadership','training');ls[T.storageId(li)]={};for(const o of li.data.options)ls[T.storageId(li)][o.response_id]=Math.max(1,Math.min(5,o.app_score+(o.app_score===2?1:0)));T.state.session.feedbackShown=true;T.renderLeadership(li);save('leadership_inline_feedback','الحكم القيادي — وضع التدريب',composed());
// results + my answers from a deliberately biased leadership response set
T.state.saved.responses.M1=T.state.saved.responses.M1||{};T.state.saved.responses.M1.leadership={exam:{}};for(const it of T.resolveItems('M1','leadership')){T.state.saved.responses.M1.leadership.exam[T.storageId(it)]={};for(const o of it.data.options)T.state.saved.responses.M1.leadership.exam[T.storageId(it)][o.response_id]=o.app_score===2?3:o.app_score;}const rr={accuracy:80,exact_match:70,overrated:12,underrated:1,rated:64,total:64,criteria:{confidence:75,generating_ideas:65,emotional_awareness:88,acquiring_information:62,continuous_improvement:70,proactivity:74,teamwork:82,leadership_presence:78},boundaries:{'1/2':90,'2/3':55,'3/4':78,'4/5':70},responseScope:'exam',mode:'exam'};T.state.saved.results.M1={leadership:{exam:rr}};clear();T.renderResult('M1','leadership',rr,false);save('leadership_results','M1 — نتيجة الحكم القيادي',composed());clear();T.renderMyAnswers('M1','leadership','exam','all');save('leadership_my_answers','M1 — إجاباتي',composed());
console.log('saved',outDir);
